package v1alpha1

import (
	"github.com/aws/aws-application-networking-k8s/pkg/k8s"
	"github.com/aws/aws-application-networking-k8s/pkg/model/core"
	"github.com/aws/aws-application-networking-k8s/pkg/utils"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	gwv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// HTTPRouteRule extends the Gateway API HTTPRouteRule with additional fields
type HTTPRouteRule struct {
	// Extends the standard Gateway API HTTPRouteRule
	gwv1.HTTPRouteRule `json:",inline"`

	// Priority defines the order in which rules are evaluated.
	// Rules with higher priority values are evaluated first.
	// If not specified, rules are evaluated in order of creation.
	// +optional
	Priority *int32 `json:"priority,omitempty"`
}

// HTTPRouteSpec extends the Gateway API HTTPRouteSpec with additional fields
type HTTPRouteSpec struct {
	// ParentRefs references the resources (usually Gateways) that a Route wants
	// to connect to.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=32
	ParentRefs []gwv1.ParentReference `json:"parentRefs"`

	// Hostnames defines a set of hostname that should match against the HTTP Host
	// header to select a HTTPRoute to process the request.
	// +kubebuilder:validation:MaxItems=16
	// +optional
	Hostnames []gwv1.Hostname `json:"hostnames,omitempty"`

	// Rules are a list of HTTP matchers, filters and actions.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	Rules []HTTPRouteRule `json:"rules"`
}

// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:resource:categories=gateway-api,shortName=hr
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
// +kubebuilder:subresource:status
type HTTPRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   HTTPRouteSpec        `json:"spec,omitempty"`
	Status gwv1.HTTPRouteStatus `json:"status,omitempty"`
}

// HTTPRouteList contains a list of HTTPRoute
// +kubebuilder:object:root=true
type HTTPRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HTTPRoute `json:"items"`
}

func init() {
	localSchemeBuilder.Register(func(scheme *runtime.Scheme) error {
		scheme.AddKnownTypes(SchemeGroupVersion,
			&HTTPRoute{},
			&HTTPRouteList{},
		)
		metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
		return nil
	})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRoute) DeepCopyInto(out *HTTPRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRoute.
func (in *HTTPRoute) DeepCopy() *HTTPRoute {
	if in == nil {
		return nil
	}
	out := new(HTTPRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteList) DeepCopyInto(out *HTTPRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteList.
func (in *HTTPRouteList) DeepCopy() *HTTPRouteList {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteSpec) DeepCopyInto(out *HTTPRouteSpec) {
	*out = *in
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]gwv1.ParentReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]gwv1.Hostname, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]HTTPRouteRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteSpec.
func (in *HTTPRouteSpec) DeepCopy() *HTTPRouteSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteRule) DeepCopyInto(out *HTTPRouteRule) {
	*out = *in
	in.HTTPRouteRule.DeepCopyInto(&out.HTTPRouteRule)
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteRule.
func (in *HTTPRouteRule) DeepCopy() *HTTPRouteRule {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteRule)
	in.DeepCopyInto(out)
	return out
}

// GetNamespacedName returns the namespaced name for the HTTPRoute
func (r *HTTPRoute) GetNamespacedName() types.NamespacedName {
	return k8s.NamespacedName(r)
}

// GetItems returns a slice of HTTPRoutes as core.Route interface
func (l *HTTPRouteList) GetItems() []core.Route {
	return utils.SliceMap(l.Items, func(r HTTPRoute) core.Route {
		baseRoute := gwv1.HTTPRoute{
			TypeMeta:   r.TypeMeta,
			ObjectMeta: r.ObjectMeta,
			Status:     r.Status,
		}
		baseRoute.Spec.ParentRefs = r.Spec.ParentRefs
		baseRoute.Spec.Hostnames = r.Spec.Hostnames
		baseRoute.Spec.Rules = convertRules(r.Spec.Rules)
		return core.NewHTTPRoute(baseRoute)
	})
}

// convertRules converts our custom HTTPRouteRule to Gateway API HTTPRouteRule
func convertRules(rules []HTTPRouteRule) []gwv1.HTTPRouteRule {
	result := make([]gwv1.HTTPRouteRule, len(rules))
	for i, rule := range rules {
		result[i] = rule.HTTPRouteRule
	}
	return result
}
